#!/usr/bin/env bash
#Fixing this container so that Nginx is running as the nginx user.

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install nginx

chown nginx:nginx /etc/nginx/nginx.conf

sudo ufw enable
sudo ufw allow 'Nginx HTTP'
sudo ufw allow ssh
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
