#!/usr/bin/env bash
#Fixing this container so that Nginx is running as the nginx user.

pkill nginx
chown nginx:nginx/etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf

sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
