#!/usr/bin/env bash
#Fixing this container so that Nginx is running as the nginx user.

pkill nginx
sudo sed -i 's/#user www-data/user nginx/'/etc/nginx/nginx.conf
chown nginx:nginx/etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf

sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo service nginx restart
