#!/usr/bin/env bash

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install apache2
sudo systemct1 start apache2
echo "Hello Holberton" | sudo tee /var/www/html/index.html
sudo service apache2 restart
