#!/usr/bin/env bash
# no comments

sudo apt update -y
sudo apt install nginx -y
sudo apt install haproxy -y

CONFIG="\
backend web-backend
	balance roundrobin
	server 4811-web-01 54.172.211.21:80 check
	server 4811-web-02 3.80.123.237:80 check
frontend http
	bind *:80
	mode http
	default_backend web-backend
"
sudo echo "$CONFIG" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
