#!/usr/bin/env bash
# keeping my Ubuntu container's Nginx installation from listening on port 80

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install nginx

sudo ufw enable
sudo ufw allow 'Nginx HTTP'
sudo ufw allow ssh
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
